owner: advancedcsg-open
repo: platform-status

# Sitelist
sites:
  - name: Advanced SSO (Production)
    url: $IDENTITY_PROD
    headers:
      - "User-Agent: Mozilla/5.0"
  - name: Advanced SSO (Module-Dev)
    url: $IDENTITY_NONPROD_URL
    headers:
      - "User-Agent: Mozilla/5.0"
  - name: MyWorkplace Login
    url: $IDENTITY_PROD_CANARY
    headers:
      - "User-Agent: Mozilla/5.0"

# Config
status-website:
  baseUrl: /platform-status
  logoUrl: https://cdn.svc.oneadvanced.com/mosaic/2.0.0/img/logo.svg
  favicon: https://www.oneadvanced.com/Static/img/icons/favicon-194x194.png
  name: Platform Status
  introTitle: "State of Platform Resources"
  introMessage: "Track the live status of select platform resources, along with a response time graph and incident tracking"
  navbar:
    - title: Status
      href: /$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  themeUrl: https://bzncdn.net/dev/adv.css
  
# Suppress repository metadata updates
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
